# Generated by Django 4.0 on 2023-10-11 22:25

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customeuser',
            managers=[
                ('objects', accounts.models.CustomeUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='id_code',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customeuser',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
