# Generated by Django 4.0 on 2023-10-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customeuser_options_alter_customeuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
