# Generated by Django 4.0 on 2023-10-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customeuser_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
