# Generated by Django 4.0 on 2023-10-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customeuser_managers_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
