# Generated by Django 4.2.3 on 2023-09-03 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 15, 50, 3, 271068)),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('which_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.comment')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
