# Generated by Django 4.2.3 on 2023-09-12 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_schedule_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 3, 53, 4, 343766)),
        ),
    ]
