# Generated by Django 4.2.3 on 2023-07-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='cotent',
            new_name='content',
        ),
    ]
