# Generated by Django 4.2.3 on 2023-07-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_rename_cotent_services_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created_data']},
        ),
    ]
